#!/usr/bin/env bash
#display numbers from 1 to 20 using while loop:
# print 4 then "bad luck from China"
# print 9 then "bad luck from Japan"
# print 17 then "bad luck from Italy"

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
