#!/usr/bin/env bash

#display the content of the current dir
# in a list format
# where only part of the name after the first dash is displayed

list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2
done
